spring:
  jpa:
    generate-ddl: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  cloudfoundry:
    skip-ssl-validation: true

  info:
    git:
      mode: full
---
spring:
  profiles: mysql
  datasource:
    url: "jdbc:mysql://localhost/music"
    driver-class-name: com.mysql.jdbc.Driver
    username:
    password: 
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
---
spring:
  profiles: postgres
  datasource:
    url: "jdbc:postgresql://localhost/music"
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.ProgressDialect
